/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ตรวจสอบสถานะการทำงานของระบบ (Health Check) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ระบบทำงานปกติและเชื่อมต่อฐานข้อมูลได้ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthSuccess"];
                    };
                };
                /** @description ระบบมีปัญหาหรือไม่สามารถเชื่อมต่อฐานข้อมูลได้ */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ดึงรายชื่อผู้ใช้งานทั้งหมด */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description รายชื่อผู้ใช้ทั้งหมดในระบบ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfileResponse"][];
                    };
                };
                /** @description ไม่พบข้อมูลผู้ใช้งานในระบบ */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description ข้อผิดพลาดทางเซิร์ฟเวอร์ */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** สร้างผู้ใช้งานใหม่ */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description สร้างผู้ใช้สำเร็จ */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            requireVerification: boolean;
                            user?: unknown;
                        };
                    };
                };
                /** @description ข้อมูลซ้ำซ้อน (Conflict) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description ข้อผิดพลาดทางเซิร์ฟเวอร์ */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/profile/:userId": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ดึงโปรไฟล์ผู้ใช้งานรายบุคคล */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description รหัสประจำตัวของผู้ใช้ (UUID) */
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ข้อมูลโปรไฟล์ของผู้ใช้รายบุคคล */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserProfileResponse"];
                    };
                };
                /** @description กรุณาระบุรหัสผู้ใช้งาน */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description ไม่พบรหัสผู้ใช้งานนี้ในฐานข้อมูล */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description ข้อผิดพลาดทางเซิร์ฟเวอร์ */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** เข้าสู่ระบบ (Login) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description สำเร็จ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description รหัสผ่านผิด */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description ยังไม่ได้ยืนยันอีเมล */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description เกิดข้อผิดพลาด */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ยืนยันอีเมลของผู้ใช้งาน */
        get: {
            parameters: {
                query: {
                    /** @description รหัสยืนยันตัวตนที่ส่งไปใน Gmail */
                    token: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description สำเร็จ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description Token ไม่ถูกต้องหรือหมดอายุ */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description เซิร์ฟเวอร์มีปัญหา */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload and compress PDF document */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description เอกสาร PDF ที่ต้องการบีบอัด
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Upload successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ดึงรายชื่อโครงการทั้งหมด */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                    search?: string;
                    status?: "draft" | "submitted" | "all_except_draft" | "all";
                    ownership?: "mine" | "team_only" | "team_and_mine" | "all";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description รายการโครงการทั้งหมด */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedProjectResponse"];
                    };
                };
                /** @description ข้อผิดพลาดเซิร์ฟเวอร์ */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example เกิดข้อผิดพลาดบางอย่าง */
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** สร้างโครงการใหม่ */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @example โครงการพัฒนาระบบให้บริการประชาชน */
                        projectName: string;
                        /** @example 2 */
                        projectTypeId?: number;
                        /**
                         * @default false
                         * @example false
                         */
                        isPublic?: boolean;
                        /** @example 1 */
                        fourQuadrantsId?: number;
                        /** @example 3 */
                        deputyGovernorId?: number;
                    };
                };
            };
            responses: {
                /** @description สร้างโครงการสำเร็จ */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            project: components["schemas"]["Project"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example เกิดข้อผิดพลาดบางอย่าง */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ดึงข้อมูลโครงการตาม ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description รหัสโครงการ (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ข้อมูลโครงการรายละเอียด */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
                /** @description รูปแบบ ID ไม่ถูกต้อง */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example เกิดข้อผิดพลาดบางอย่าง */
                            message: string;
                        };
                    };
                };
                /** @description ไม่พบข้อมูลโครงการ */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example เกิดข้อผิดพลาดบางอย่าง */
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** ลบข้อมูลโครงการ */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description รหัสโครงการ (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ลบสำเร็จ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description ไม่พบข้อมูลโครงการ */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example เกิดข้อผิดพลาดบางอย่าง */
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** อัปเดตข้อมูลโครงการ */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description รหัสโครงการ (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @example โครงการพัฒนาระบบให้บริการประชาชน */
                        projectName?: string;
                        /** @example 2 */
                        projectTypeId?: number;
                        /**
                         * @default false
                         * @example false
                         */
                        isPublic?: boolean;
                        /** @example 1 */
                        fourQuadrantsId?: number;
                        /** @example 3 */
                        deputyGovernorId?: number;
                    };
                };
            };
            responses: {
                /** @description อัปเดตสำเร็จ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            project: components["schemas"]["Project"];
                        };
                    };
                };
                /** @description ไม่พบข้อมูลโครงการ */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example เกิดข้อผิดพลาดบางอย่าง */
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/projects/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** อัปเดตสถานะโครงการ (Admin/Head) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description รหัสโครงการ (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @example 2 */
                        projectStatusId: number;
                        projectTypeId?: number;
                        /** @example ผ่านการอนุมัติขั้นต้น */
                        remark?: string;
                    };
                };
            };
            responses: {
                /** @description สำเร็จ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/projects/{id}/type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** อัปเดตประเภทโครงการ */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description รหัสโครงการ (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @example 3 */
                        projectTypeId: number;
                    };
                };
            };
            responses: {
                /** @description สำเร็จ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/projects/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** มอบหมายงานโครงการให้นักวิเคราะห์ */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description รหัสโครงการ (UUID) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description UUID ของนักวิเคราะห์
                         */
                        analystId: string;
                    };
                };
            };
            responses: {
                /** @description สำเร็จ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/proposals/drafts/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user's proposal drafts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: unknown;
                            message?: string;
                            success?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/projects/{projectId}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project UUID */
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Proposal draft */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: unknown;
                            message?: string;
                            success?: boolean;
                        };
                    };
                };
                /** @description Invalid project id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project UUID */
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Initialized proposal draft */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: unknown;
                            message?: string;
                            success?: boolean;
                        };
                    };
                };
                /** @description Invalid project id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project UUID */
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        projectId?: string;
                        currentStep?: number | null;
                        draftPayload?: {
                            [key: string]: unknown;
                        };
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                /** @description Auto-saved proposal draft */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: unknown;
                            message?: string;
                            success?: boolean;
                        };
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/proposals/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project UUID */
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Submitted proposal */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: unknown;
                            message?: string;
                            success?: boolean;
                        };
                    };
                };
                /** @description Invalid project id */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/projects/{projectId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project UUID */
                    projectId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        projectName: string;
                        agencyName: string;
                        headOfAgency: string;
                        dcioName: string;
                        projectManager: string;
                        totalBudget: number;
                        /** @default [] */
                        budgetsByYear?: {
                            /** Format: uuid */
                            id?: string;
                            year: number;
                            amount: number;
                            budgetType: string;
                        }[];
                        background: string;
                        objective: string;
                        target: string;
                        scope: string;
                        /** @enum {string} */
                        projectType: "NEW" | "REPLACEMENT" | "CONTINUOUS";
                        currentSystemStatus: string;
                        currentProblems: string;
                        /** @default [] */
                        relatedProjects?: {
                            /** Format: uuid */
                            id?: string;
                            projectName: string;
                            agency: string;
                            fiscalYear: string;
                            relationType: string;
                            remark?: string;
                        }[];
                        /** @default [] */
                        manpower?: {
                            /** Format: uuid */
                            id?: string;
                            agencyPart: string;
                            positionLimit: number | null;
                            occupied: number | null;
                            vacant: number | null;
                        }[];
                        /** @default [] */
                        existingEquipment?: {
                            /** Format: uuid */
                            id?: string;
                            itemName: string;
                            ageYears: number | null;
                            quantity: number | null;
                            user: string;
                            location: string;
                            remark?: string;
                        }[];
                        /** @default false */
                        isBmaPlan?: boolean;
                        /** @default false */
                        isAgencyPlan?: boolean;
                        agencyStrategy?: string;
                        agencyIssue?: string;
                        agencyKpi?: string;
                        /** @default false */
                        isGovernorPolicy?: boolean;
                        governorPolicyCode?: string;
                        governorPolicyName?: string;
                        obstacleLaws?: string;
                        appArchitecture: string;
                        dataOwner: string;
                        dataExchangePlan: string;
                        /** @default [] */
                        hardwareCosts?: {
                            /** Format: uuid */
                            id?: string;
                            itemName: string;
                            quantity: number;
                            unitPrice: number | null;
                            /** @enum {string} */
                            referenceType: "MDES" | "MARKET" | "PREVIOUS" | "OTHER";
                            mdesMonth?: string;
                            mdesYear?: string;
                            mdesItemNo?: string;
                            marketCount?: number | null;
                            marketCompany?: string;
                            prevProject?: string;
                            prevYear?: string;
                            otherDetail?: string;
                        }[];
                        /** @default [] */
                        softwareCosts?: {
                            /** Format: uuid */
                            id?: string;
                            itemName: string;
                            quantity: number;
                            unitPrice: number | null;
                            /** @enum {string} */
                            referenceType: "MDES" | "MARKET" | "PREVIOUS" | "OTHER";
                            mdesMonth?: string;
                            mdesYear?: string;
                            mdesItemNo?: string;
                            marketCount?: number | null;
                            marketCompany?: string;
                            prevProject?: string;
                            prevYear?: string;
                            otherDetail?: string;
                        }[];
                        /** @default [] */
                        personnelCoreCosts?: {
                            /** Format: uuid */
                            id?: string;
                            /** @enum {string} */
                            personnelType: "CORE" | "ASST" | "SUPP";
                            position: string;
                            degree: string;
                            fieldOfStudy?: string;
                            experienceYears: number | null;
                            baseSalary: number;
                            multiplier?: number | null;
                            personCount: number;
                            durationMonths: number;
                        }[];
                        /** @default [] */
                        personnelAsstCosts?: {
                            /** Format: uuid */
                            id?: string;
                            /** @enum {string} */
                            personnelType: "CORE" | "ASST" | "SUPP";
                            position: string;
                            degree: string;
                            fieldOfStudy?: string;
                            experienceYears: number | null;
                            baseSalary: number;
                            multiplier?: number | null;
                            personCount: number;
                            durationMonths: number;
                        }[];
                        /** @default [] */
                        personnelSuppCosts?: {
                            /** Format: uuid */
                            id?: string;
                            /** @enum {string} */
                            personnelType: "CORE" | "ASST" | "SUPP";
                            position: string;
                            degree: string;
                            fieldOfStudy?: string;
                            experienceYears: number | null;
                            baseSalary: number;
                            multiplier?: number | null;
                            personCount: number;
                            durationMonths: number;
                        }[];
                        /** @default [] */
                        personnelResponsibilities?: {
                            /** Format: uuid */
                            id?: string;
                            position: string;
                            responsibility: string;
                        }[];
                        /** @default [] */
                        trainingCourses?: {
                            /** Format: uuid */
                            id?: string;
                            courseName: string;
                            trainingMethod: string;
                            /** @enum {string} */
                            locationType: "GOVERNMENT" | "PRIVATE";
                            /** @default false */
                            hasSpeakerCost?: boolean;
                            speakerReason?: string;
                            /** @default [] */
                            speakerCosts?: {
                                /** Format: uuid */
                                id?: string;
                                itemName: string;
                                hours: number;
                                ratePerHour: number | null;
                                days: number;
                            }[];
                            /** @default [] */
                            foodCosts?: {
                                /** Format: uuid */
                                id?: string;
                                /** @enum {string} */
                                itemName: "PARTIAL_MEAL" | "FULL_MEAL" | "SNACK" | "OTHER";
                                mealsCount: number | null;
                                ratePerMeal: number | null;
                                traineesCount: number | null;
                                days: number | null;
                            }[];
                        }[];
                        /** @default [] */
                        otherCosts?: {
                            /** Format: uuid */
                            id?: string;
                            itemName: string;
                            quantity: number;
                            unitPrice: number | null;
                            remark?: string;
                            /** @enum {string} */
                            costType: "IT" | "NON_IT";
                        }[];
                        durationDays: number;
                        /** @default [] */
                        ictPersonnel?: {
                            /** Format: uuid */
                            id?: string;
                            position: string;
                            level: string;
                            count: number;
                        }[];
                        /** @default [] */
                        cloudRequests?: {
                            /** Format: uuid */
                            id?: string;
                            systemName: string;
                            /** Format: date-time */
                            requestedServiceDate: string | null;
                            /** Format: date-time */
                            recordedRequestDate: string | null;
                            /** @default [] */
                            vms?: {
                                /** Format: uuid */
                                id?: string;
                                vmDescription: string;
                                osDatabase: string;
                                vcpu: number | null;
                                ramGb: number | null;
                                gpuGb: number | null;
                                storageGb: number | null;
                                price: number | null;
                            }[];
                        }[];
                        otherReadiness?: string;
                        expectedBenefits: string;
                        isInRoadmap: boolean;
                    };
                };
            };
            responses: {
                /** @description Submitted proposal */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: unknown;
                            message?: string;
                            success?: boolean;
                        };
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ดึงข้อมูลการประชุมทั้งหมด */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description รายการการประชุม */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Meeting"][];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example เกิดข้อผิดพลาดบางอย่าง */
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** สร้างการประชุมใหม่ */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateMeeting"];
                };
            };
            responses: {
                /** @description สร้างสำเร็จ */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Meeting"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example เกิดข้อผิดพลาดบางอย่าง */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ดึงข้อมูลการประชุมตาม ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description รายละเอียดการประชุม */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Meeting"];
                        };
                    };
                };
                /** @description ไม่พบข้อมูล */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example เกิดข้อผิดพลาดบางอย่าง */
                            message: string;
                        };
                    };
                };
            };
        };
        /** อัปเดตข้อมูลการประชุม */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateMeeting"];
                };
            };
            responses: {
                /** @description อัปเดตสำเร็จ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Meeting"];
                        };
                    };
                };
                /** @description ไม่พบข้อมูล */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example เกิดข้อผิดพลาดบางอย่าง */
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        /** ลบการประชุม */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ลบสำเร็จ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description ไม่พบข้อมูล */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example เกิดข้อผิดพลาดบางอย่าง */
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/agendas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** สร้างวาระการประชุม */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateAgenda"];
                };
            };
            responses: {
                /** @description สร้างวาระสำเร็จ */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Agenda"];
                        };
                    };
                };
                /** @description ไม่พบการประชุม */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example เกิดข้อผิดพลาดบางอย่าง */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meetingId}/agendas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ดึงวาระทั้งหมดในการประชุมหนึ่งๆ */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    meetingId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description รายการวาระการประชุม */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Agenda"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/agendas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** อัปเดตข้อมูลวาระการประชุม */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateAgenda"];
                };
            };
            responses: {
                /** @description อัปเดตสำเร็จ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Agenda"];
                        };
                    };
                };
                /** @description ไม่พบข้อมูล */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example เกิดข้อผิดพลาดบางอย่าง */
                            message: string;
                        };
                    };
                };
            };
        };
        post?: never;
        /** ลบวาระการประชุม */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ลบสำเร็จ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
                /** @description ไม่พบข้อมูล */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example เกิดข้อผิดพลาดบางอย่าง */
                            message: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/cloud-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ดึงข้อมูลการร้องขอ Cloud และ VM (สำหรับ Internal API) */
        get: {
            parameters: {
                query?: {
                    /** @description กรองด้วย ID โครงการ (UUID) */
                    projectId?: string;
                    /** @description กรองด้วยรหัสโครงการ (เช่น BMA-69-0001) */
                    projectCode?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ข้อมูล Cloud Requests พร้อมรายละเอียด VM */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CloudRequest"][];
                        };
                    };
                };
                /** @description ถูกปฏิเสธเนื่องจาก IP ไม่อยู่ใน Whitelist */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthSuccess: {
            /** @example ok */
            status: string;
            /** @example connected */
            database: string;
            /** @example 2026-06-12T12:00:00.000Z */
            timestamp: string;
        };
        HealthError: {
            /** @example error */
            status: string;
            /** @example disconnected */
            database: string;
        };
        UserProfileResponse: {
            /** Format: uuid */
            userId: string;
            username: string;
            firstName: string;
            lastName: string;
            email: string;
            position: string | null;
            level: string | null;
            managementPosition: string | null;
            divisionId: number | null;
            mobilePhone: string | null;
            officePhone: string | null;
            internalExtension: string | null;
            isActive: boolean;
            /** Format: date-time */
            lastLogin: string | null;
            isVerified: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description ข้อมูลหน่วยงานและต้นสังกัด */
            division: {
                /** @example 1 */
                divisionId: number;
                /** @example กองยุทธศาสตร์ดิจิทัล */
                divisionName: string;
                /** @example 1 */
                departmentId: number;
                /** @example สำนักดิจิทัล */
                departmentName: string;
            } | null;
            /** @description สิทธิ์การใช้งานทั้งหมดของผู้ใช้ */
            roles: {
                /** @example 1 */
                roleId: number;
                /** @example USER */
                roleName: string;
            }[];
        };
        ErrorResponse: {
            /** @example ข้อมูลซ้ำ */
            error: string;
            /** @example email */
            field?: string;
        };
        CreateUserRequest: {
            username: string;
            password: string;
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            position?: string | null;
            level?: string | null;
            managementPosition?: string | null;
            divisionId?: number | null;
            mobilePhone?: string | null;
            officePhone?: string | null;
            internalExtension?: string | null;
            /**
             * @default [
             *       1
             *     ]
             * @example [
             *       1
             *     ]
             */
            roleIds: number[];
        };
        LoginResponse: {
            message: string;
            token: string;
            user: {
                userId: string;
                username: string;
                firstName: string;
                lastName: string;
            };
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        PaginatedProjectResponse: {
            data: components["schemas"]["Project"][];
            pagination: {
                total: number;
                page: number;
                limit: number;
                totalPages: number;
            };
        };
        Project: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /** @example BMA-69-0001 */
            projectCode: string | null;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            userId: string;
            /** @example 12 */
            divisionId: number;
            /** @example 1 */
            projectStatusId: number | null;
            /** @example 2 */
            projectTypeId: number | null;
            /** @example 1 */
            fourQuadrantsId: number | null;
            /** @example 3 */
            deputyGovernorId: number | null;
            /** @example null */
            externalTaskId: string | null;
            /** @example โครงการพัฒนาระบบให้บริการประชาชน */
            projectName: string | null;
            /** @example โครงการพัฒนาระบบให้บริการประชาชน */
            projectNameOriginal: string | null;
            /** @example 5000000.00 */
            initialRequestedBudget: string | null;
            /** @example 4500000.00 */
            latestApprovedBudget: string | null;
            /**
             * Format: uuid
             * @example null
             */
            analystId: string | null;
            /**
             * Format: uuid
             * @example null
             */
            assignedBy: string | null;
            /**
             * Format: date-time
             * @example null
             */
            assignedAt: string;
            /** @example false */
            isPublic: boolean;
            /** @example null */
            publicToken: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * Format: uuid
             * @example null
             */
            updatedBy: string | null;
            /** @description ข้อมูลส่วนราชการเจ้าของโครงการ */
            division: {
                id: number;
                name: string;
                departmentId: number | null;
                departmentName: string | null;
            } | null;
            /** @description สถานะโครงการ */
            status: {
                id: number;
                name: string;
            } | null;
            /** @description ประเภทโครงการ */
            projectType: {
                id: number;
                name: string;
            } | null;
            /** @description ผู้สร้างโครงการ */
            owner: {
                /** Format: uuid */
                userId: string;
                firstName: string;
                lastName: string;
            } | null;
        };
        Meeting: {
            /** Format: uuid */
            id: string;
            meetingNo: string;
            title: string;
            meetingTypeId: number;
            /** Format: date-time */
            meetingDate: string;
            location?: string | null;
            meetingStatusId: number;
            /** Format: uuid */
            createdBy: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: uuid */
            updatedBy?: string | null;
        };
        CreateMeeting: {
            meetingNo: string;
            title: string;
            meetingTypeId: number;
            /** Format: date-time */
            meetingDate: string;
            location?: string;
            meetingStatusId: number;
        };
        UpdateMeeting: {
            meetingNo?: string;
            title?: string;
            meetingTypeId?: number;
            /** Format: date-time */
            meetingDate?: string;
            location?: string;
            meetingStatusId?: number;
        };
        Agenda: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            meetingId: string;
            /** Format: uuid */
            projectId?: string | null;
            agendaNumber: string;
            agendaTypeId: number;
            title: string;
            description?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateAgenda: {
            /** Format: uuid */
            meetingId: string;
            /** Format: uuid */
            projectId?: string;
            agendaNumber: string;
            agendaTypeId: number;
            title: string;
            description?: string;
        };
        UpdateAgenda: {
            /** Format: uuid */
            projectId?: string;
            agendaNumber?: string;
            agendaTypeId?: number;
            title?: string;
            description?: string;
        };
        CloudRequest: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description รหัสโครงการ (BMA-YY-XXXX) */
            projectCode: string | null;
            /** @description ชื่อโครงการ */
            projectName: string | null;
            /** @description ชื่อหน่วยงาน/ส่วนราชการ */
            agencyName: string | null;
            /** @description ราคารวมของ VM ทั้งหมดใน Request นี้ */
            totalPrice: string;
            systemName: string;
            /** Format: date-time */
            requestedServiceDate: string | null;
            /** Format: date-time */
            recordedRequestDate: string | null;
            /** @default [] */
            vms: {
                /** Format: uuid */
                id: string;
                vmDescription: string;
                osDatabase: string | null;
                vcpu: number;
                ramGb: number;
                gpuGb: number;
                storageGb: number;
                price: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
